---
title: "Operation Status Analysis and Delay Prediction of NYC School Bus "
---



# Overview of the project 

For many students, school bus is the only available method of transportation to and from school. Improving the operation condition and safety of school bus has always been an important topic. 

The Office of Pupil Transportation(OPT) administers school bus service to New York City schools for students attending both public and non-public schools, and it aims to use the Bus Breakdown and Delay system to inform parents who call with questions regarding bus service. The Bus Breakdown and Delay system collects information from school bus vendors operating out in the field in real time about the occur and inform time, delay duration, breakdown and delay reasons, and other operation information.

Using the data collected by the Bus Breakdown and Delay System of OPT, our project focuses on exploratory analyses and anticipation. Within the exploratory analysis, we compare different school bus companies by delay duration, reaction time and work fault. We also compare route services by the odds of notifying and the effect of route planning. Within the anticipation part, we build a model to predict the delay duration. Office of Pupil Transportation would be able to get the expected delay duration with this model and inform the parents who call.



# Data

Our data consist of breakdown and delay information of school buses in New York during 2015-2016, 2016-2017 and 2017-2018 school years (except July, August and September), including 168462 observations of 20 variables about the occur and inform time, delay duration, breakdown and delay reasons, and other operation information. 

It is real time updated and can be downloaded from the NYC Open Data.

Find our data [here](Bus_Breakdown_and_Delays.csv).



# Appraoches

* Clean and prepare the data for further analysis by string processing and data type converting

* Describe the data according to time, reasons, companies and other categorical variables we are interested in, visualized by barplots, scatter plots and tables

* Build up and validate a logistics regression model to predict the range of delay duration based on the predictors we select


# Visualizations

* Our plotly dashboard is [here](nyc_bus_dashboard.html)


# Results

* The occurence of school bus delays mainly centers around *7:00-8:00am* and *2:00-3:00pm*, which are the commonsensible rush hours. 

* The boros which have the most frequent delays are *Brooklyn* and *Bronx*.The boros which have the least frequent delays are *Staten Island* and *Westchester*. This result indicates the traffic condition of these boros.

* The most common reasons for breakdown are *mechanical problem*, *won’t start* and *flat tire*. The most common reason for delay is *heavy traffic*.

* *Accident* and *mechanical problem* tend to cause the longest delay duration while *delayed by school* and *heavy traffic* tend to have the shortest delay duration.

* *“FORTUNA BUS COMPANY”* has the longest reaction time of three and a half hours, followed by *“R & C TRANSIT, INC.”*, *“SMART PICK”* and *“PENNY TRANSPORTATION”*.

* The ratio of work faults(reaction time is negative or more than one day) is quite small generally. The company *“IC BUS INC.”* has the largest ratio of work faults, followed by *“GRANDPA`S BUS CO., INC.”* and *“ACME BUS CORP.”*.

* The route service for Pre-K has a much higher odds of notifying and shorter average delay duration because of running late compared to School-Age. Route planning has a negative effect on the school bus arriving in time because of inflexibility.

* In our logistics regression model, we can predict the range of duration of delay based on the predictors we choose. Our model has prediction accuracy of apporximately 62%.


